baseURL: "https://mathiasgoris.netlify.app"
languageCode: "en-us"
publishDir: "docs"
title: "Mathias Goris"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Mathias Goris"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Mathias Goris" # Brand name for the brand | default is the title variable
    disableSearch: false
    searchPlaceholder: "Search blog..."
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Mathias Goris."
   # subtitle: "I'm an IT student."
    content: "I am a passionate IT student with strong programming skills. My goal is to create innovative technological solutions and make complex technical concepts understandable."
    image: /images/portfolio-image.png
    bottomImage:
      enable: true
      roundImage: true # Make hero image circular | default false
      size: 200 # Size of the image | default 100
    button:
      enable: true
      name: "My Resume"
      url: "MathiasGorisCv.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/mathias-goris-4574572a0

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/portfolio-image-circle.png"
    content: |-
      I am a student specializing in software engineering with a passion for web development. Currently, I am pursuing my Bachelor of Applied Computer Science at Howest University of Applied Sciences.

      In addition to my studies, I enjoy working on personal projects and participating in hackathons. In my free time, I love creating small games using Unity, combining my technical skills with creativity to build engaging and interactive experiences.

    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Vue"
        - "Sass"
        - "TypeScript"
        - "React"
        - "Laravel"
        - ".NET"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "IT Support"
        company: "Beego"
        companyUrl: "https://beego.be"
        date: "2023 - present"
        content: "At Beego, I assist people with their IT problems, further enhancing my own IT problem-solving skills"

      - job: "Cashier"
        company: "Alma"
        companyUrl: "https://www.carrefour.be"
        date: "2021 - 2022"
       # info:
        #  enable: true
         # content: I worked as a software developer for more than one year in Amazon.
        content: "During my two-year involvement with Alma, I gained valuable experience that enhanced my skills in customer service and teamwork"

      - job: "Gardener"
        company: "AGO jobs"
        companyUrl: "https://www.ago.jobs"
        date: "JUL 2020 - AUG 2020"
        content: "During my time at AGO jobs, I worked as a gardener, gaining experience in teamwork and instilling a strong work ethic."

      - job: "Bartender"
        company: "Belshof"
        companyUrl: "http://taverne-belshof.be"
        date: "JUL 2019 - AUG 2019"
        content: "During my time at Belshof, I worked in a bar, gaining experience in customer service and teamwork."

     
  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor Toegepaste Informatica"
        school:
          name: "Howest hogeschool"
          url: "https://www.howest.be/nl"
        date: "2021 - 2024"
        content: |-
          During my studies at Howest, I specialized in software engineering. I gained extensive knowledge in designing, developing, and testing software applications. Additionally, I completed various projects, including:

          - Development of a web-based Monopoly game.
          - Creation of a Customer Relationship Management (CRM) system.
          - Implementation of a mobile calendar application.
          - Development of a smart home application.

          I also actively participated in workshops and hackathons, which allowed me to further hone my skills and collaborate with other enthusiastic students and professionals.

        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"

      - title: "Acccounting and IT"
        school:
          name: "Sint-Maria Geel"
          url: "https://kogeka.be/sintmaria/"
        date: "2019 - 2021"
        content: This is what I did in the 5th and 6th year of secondary school. Here, I learned the basics of programming.
  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:mathias.goris@outlook.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Blogs
      enable: true
      disableFeaturedImage: false
    

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
